### ISSUE TITLE
Not working for latest mkdocs 1.4.0

### ISSUE THREAD

**Issue by dtcooper** [oprypin/mkdocs-same-dir#4]
Title says it all! Thanks for the great package.

**Comment by oprypin** [comment]
Woops. Broke my own plugin :sweat_smile: 

Thanks much for the report! Fixed and released.

**Comment by oprypin** [comment]
> Broke my own plugin

https://github.com/mkdocs/mkdocs/commit/aafd308660a88385f80b6fb7708c02d6bf21b1d4#diff-685a203254588194fa9c3c97a67d1b8b5609f807541cea23b9f8cd25baa67cecR385

**Comment by dtcooper** [comment]
Cheers thanks for the speedy fix! Appreciate it.
