### ISSUE TITLE
Feature request: Correct "edit this page" button when `repo_url` is set

### ISSUE THREAD

**Issue by rmartine-ias** [oprypin/mkdocs-same-dir#5]
The "Edit this page" button currently displayed on the generated docs page when `repo_url` is set in `mkdocs.yml` is not linking to the correct page when `mkdocs-same-dir` is in use.

<img width="144" alt="Screenshot 2023-04-26 at 11 23 51 AM" src="https://user-images.githubusercontent.com/107639398/234654460-97a1a920-6a6a-4f97-96bf-3a7f1a38121b.png">

For instance, if the URL is `https://github.com/org/repo/edit/master/docs/README.md`, the button currently links to `https://github.com/org/repo/edit/master/README.md`. This feature request is for the plugin to patch the button to link to the actual URL, instead of the one containing `docs/`.

If this is a desired feature, I can probably pull some time to work on it in the next few weeks.

**Comment by oprypin** [comment]
Thanks for the inquiry.

MkDocs actually has no awareness of what the correct directory is. Regardless of this plugin, if you put your documentation into a `crocs/` directory and not `docs/`, the default value of [`edit_uri`](https://www.mkdocs.org/user-guide/configuration/#edit_uri) is `'edit/master/docs/'`. (or I usually set it to `blob/master/docs/`).

As such, you can just add `edit_uri: blob/master/` to your MkDocs config if you're using the root directory.

**Comment by rmartine-ias** [comment]
Thank you so much! Making this change.
